name: sv_client
version: 1.0.0
authors:
  - Robert Åkerblom-Andersson <robert@sourcevoid.com>
environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: any
  http: "^0.11.3+2"
  mongo_dart: "^0.2.5+1"
  bson: "^0.2.0"
  usage: "^2.2.2"
  crypto: ">=0.9.2 <3.0.0"
  convert: ">=1.0.0 <3.0.0"
  sv_models:
    path: ../sv_models

analyzer:
  strong-mode: true

